#!/usr/bin/env groovy

node ('docker'){
    stage('Checkout') {

        checkout scmGit(
                        branches: 
                        [[name: 'maniako97/jenkinsfile']], 
                        extensions: [], 
                        userRemoteConfigs: [[url: 'https://github.com/maniako97/cloudcamp-jenkins-lab']]
                        ) 
        
    }

    stage ('Build') {
        sh 'docker build -t "app/python-hello-world:1.0.0-beta.1" -f _scm_docker/Dockerfile _scm_docker/'
    }
}
